#!/usr/bin/env bash
set -Eeuo pipefail

readonly SCRIPT_NAME="$(basename "$0")"
readonly ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly SOURCE_ROOT_CMD="$ROOT_DIR/scripts/e2e/target/adc-target-smoke-root.sh"
readonly DEFAULT_LIBEXEC_DIR="/usr/local/libexec/agent-debug-compass"
readonly DEFAULT_SUDOERS_NAME="adc-targetd-smoke"

mode="dry-run"
remove="no"
target_user="${SUDO_USER:-$(id -un)}"
libexec_dir="$DEFAULT_LIBEXEC_DIR"
sudoers_name="$DEFAULT_SUDOERS_NAME"

usage() {
  cat <<'USAGE'
Usage:
  scripts/install/install-target-smoke-sudoers.sh [--dry-run]
  sudo scripts/install/install-target-smoke-sudoers.sh --apply [--user USER]
  sudo scripts/install/install-target-smoke-sudoers.sh --remove [--user USER]

Options:
  --dry-run              Print the install plan. Default.
  --apply                Install root-owned smoke command and sudoers rule.
  --remove               Remove the sudoers rule and installed smoke command.
  --user USER            User allowed to run the smoke command without a password.
                         Defaults to SUDO_USER when run via sudo.
  --libexec-dir DIR      Install directory. Default: /usr/local/libexec/agent-debug-compass.
  --sudoers-name NAME    File name under /etc/sudoers.d. Default: adc-targetd-smoke.
  -h, --help             Show help.

The sudoers rule grants NOPASSWD only for:
  /usr/local/libexec/agent-debug-compass/adc-target-smoke-root

It does not grant arbitrary shell access, sudo to repository scripts, or sudo to
build tools. The installed command itself requires --allow-privileged-smoke.
USAGE
}

log() {
  printf '[%s] %s\n' "$SCRIPT_NAME" "$*"
}

die() {
  printf '[%s] ERROR: %s\n' "$SCRIPT_NAME" "$*" >&2
  exit 1
}

run() {
  log "+ $*"
  "$@"
}

sudo_cmd() {
  if [[ "$(id -u)" == "0" ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run)
        mode="dry-run"
        ;;
      --apply)
        mode="apply"
        ;;
      --remove)
        mode="apply"
        remove="yes"
        ;;
      --user)
        target_user="${2:?missing user}"
        shift
        ;;
      --libexec-dir)
        libexec_dir="${2:?missing directory}"
        shift
        ;;
      --sudoers-name)
        sudoers_name="${2:?missing sudoers name}"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown argument: $1"
        ;;
    esac
    shift
  done
}

validate_inputs() {
  [[ -f "$SOURCE_ROOT_CMD" ]] || die "source smoke command not found: $SOURCE_ROOT_CMD"
  [[ "$target_user" != "root" ]] || die "--user must name the non-root operator"
  [[ "$target_user" =~ ^[A-Za-z_][A-Za-z0-9_.-]*[$]?$ ]] || die "unsafe user name: $target_user"
  [[ "$sudoers_name" =~ ^[A-Za-z0-9_.-]+$ ]] || die "unsafe sudoers file name: $sudoers_name"
  [[ "$libexec_dir" == /* ]] || die "--libexec-dir must be absolute"
  [[ "$libexec_dir" != *" "* ]] || die "--libexec-dir must not contain spaces"
  command -v install >/dev/null 2>&1 || die "install command not found"
  if [[ "$mode" == "apply" ]]; then
    command -v visudo >/dev/null 2>&1 || die "visudo command not found"
  fi
}

installed_cmd() {
  printf '%s/adc-target-smoke-root\n' "$libexec_dir"
}

sudoers_path() {
  printf '/etc/sudoers.d/%s\n' "$sudoers_name"
}

render_sudoers() {
  local cmd
  cmd="$(installed_cmd)"
  cat <<SUDOERS
# Generated by adc-targetd install-target-smoke-sudoers.sh.
# Grants ${target_user} passwordless sudo only for the fixed root smoke entrypoint.
# The entrypoint validates subcommands and requires --allow-privileged-smoke.
${target_user} ALL=(root) NOPASSWD: ${cmd}
SUDOERS
}

print_plan() {
  log "mode: $mode"
  log "remove: $remove"
  log "target user: $target_user"
  log "source command: $SOURCE_ROOT_CMD"
  log "installed command: $(installed_cmd)"
  log "sudoers file: $(sudoers_path)"
  log "sudoers content:"
  render_sudoers
  log "post-install smoke check:"
  printf '  %s\n' "sudo -n $(installed_cmd) --allow-privileged-smoke self-check"
}

apply_install() {
  local cmd sudoers tmp
  cmd="$(installed_cmd)"
  sudoers="$(sudoers_path)"

  run sudo_cmd install -d -o root -g root -m 0755 "$libexec_dir"
  run sudo_cmd install -o root -g root -m 0755 "$SOURCE_ROOT_CMD" "$cmd"

  tmp="$(mktemp)"
  render_sudoers >"$tmp"
  run sudo_cmd visudo -cf "$tmp"
  run sudo_cmd install -o root -g root -m 0440 "$tmp" "$sudoers"
  rm -f "$tmp"

  log "installed. Verify with:"
  printf '  %s\n' "sudo -n $cmd --allow-privileged-smoke self-check"
}

apply_remove() {
  local cmd sudoers
  cmd="$(installed_cmd)"
  sudoers="$(sudoers_path)"
  run sudo_cmd rm -f "$sudoers"
  run sudo_cmd rm -f "$cmd"
  run sudo_cmd rmdir "$libexec_dir" 2>/dev/null || true
  log "removed sudoers rule and installed smoke command"
}

main() {
  parse_args "$@"
  validate_inputs
  print_plan
  if [[ "$mode" != "apply" ]]; then
    log "dry-run only; pass --apply or --remove to change the system"
    return 0
  fi
  if [[ "$remove" == "yes" ]]; then
    apply_remove
  else
    apply_install
  fi
}

main "$@"
