#ifndef ADC_SENSOR_PROBE_H
#define ADC_SENSOR_PROBE_H

#include <linux/ioctl.h>
#include <linux/types.h>

#define ADC_SENSOR_PROBE_IOC_MAGIC 'R'
#define ADC_SENSOR_PROBE_IOC_ARM _IO(ADC_SENSOR_PROBE_IOC_MAGIC, 1)
#define ADC_SENSOR_PROBE_IOC_DISARM _IO(ADC_SENSOR_PROBE_IOC_MAGIC, 2)
#define ADC_SENSOR_PROBE_IOC_SELFTEST _IO(ADC_SENSOR_PROBE_IOC_MAGIC, 3)
#define ADC_SENSOR_PROBE_IOC_GET_DROPS _IOR(ADC_SENSOR_PROBE_IOC_MAGIC, 4, __u64)

#endif
